-- 0011_cosmetics_seed.sql — 100 curated cosmetics. store=buyable w/ CRED; supporter/award/earned = granted.
insert into cosmetics (id,name,category,rarity,cred_cost,supporter_only,source,description) values
('emblem_corner_crown','Corner Crown','emblem','uncommon',500,false,'store','Uncommon emblem cosmetic. Flair only — no gameplay effect.'),
('emblem_the_re_up','The Re-Up','emblem','rare',1200,false,'store','Rare emblem cosmetic. Flair only — no gameplay effect.'),
('emblem_kilo_club','Kilo Club','emblem','epic',3000,false,'store','Epic emblem cosmetic. Flair only — no gameplay effect.'),
('emblem_burner','Burner','emblem','common',250,false,'store','Common emblem cosmetic. Flair only — no gameplay effect.'),
('emblem_evidence_bag','Evidence Bag','emblem','uncommon',500,false,'store','Uncommon emblem cosmetic. Flair only — no gameplay effect.'),
('emblem_trap_king','Trap King','emblem','legendary',7000,false,'store','Legendary emblem cosmetic. Flair only — no gameplay effect.'),
('emblem_ghost_protocol','Ghost Protocol','emblem','epic',3000,false,'store','Epic emblem cosmetic. Flair only — no gameplay effect.'),
('emblem_wolf_of_wolfline','Wolf of Wolfline','emblem','rare',1200,false,'store','Rare emblem cosmetic. Flair only — no gameplay effect.'),
('emblem_concrete_rose','Concrete Rose','emblem','rare',1200,false,'store','Rare emblem cosmetic. Flair only — no gameplay effect.'),
('emblem_rust_belt','Rust Belt','emblem','common',250,false,'store','Common emblem cosmetic. Flair only — no gameplay effect.'),
('emblem_nightshift','Nightshift','emblem','uncommon',500,false,'store','Uncommon emblem cosmetic. Flair only — no gameplay effect.'),
('emblem_the_connect','The Connect','emblem','legendary',7000,false,'store','Legendary emblem cosmetic. Flair only — no gameplay effect.'),
('emblem_skeleton_key','Skeleton Key','emblem','epic',3000,false,'store','Epic emblem cosmetic. Flair only — no gameplay effect.'),
('emblem_dead_presidents','Dead Presidents','emblem','rare',1200,false,'store','Rare emblem cosmetic. Flair only — no gameplay effect.'),
('emblem_cut_cook','Cut & Cook','emblem','uncommon',500,false,'store','Uncommon emblem cosmetic. Flair only — no gameplay effect.'),
('emblem_steel_city','Steel City','emblem','common',250,false,'store','Common emblem cosmetic. Flair only — no gameplay effect.'),
('emblem_bag_secured','Bag Secured','emblem','rare',1200,false,'store','Rare emblem cosmetic. Flair only — no gameplay effect.'),
('emblem_no_face','No Face','emblem','mythic',15000,false,'store','Mythic emblem cosmetic. Flair only — no gameplay effect.'),
('emblem_the_ledger','The Ledger','emblem','epic',3000,false,'store','Epic emblem cosmetic. Flair only — no gameplay effect.'),
('emblem_off_the_books','Off the Books','emblem','uncommon',500,false,'store','Uncommon emblem cosmetic. Flair only — no gameplay effect.'),
('title_the_connect','The Connect','title','legendary',7000,false,'store','Legendary title cosmetic. Flair only — no gameplay effect.'),
('title_ghost','Ghost','title','epic',3000,false,'store','Epic title cosmetic. Flair only — no gameplay effect.'),
('title_trap_star','Trap Star','title','rare',1200,false,'store','Rare title cosmetic. Flair only — no gameplay effect.'),
('title_made','Made','title','legendary',7000,false,'store','Legendary title cosmetic. Flair only — no gameplay effect.'),
('title_kingpin','Kingpin','title','mythic',15000,false,'store','Mythic title cosmetic. Flair only — no gameplay effect.'),
('title_corner_boy','Corner Boy','title','common',250,false,'store','Common title cosmetic. Flair only — no gameplay effect.'),
('title_the_plug','The Plug','title','epic',3000,false,'store','Epic title cosmetic. Flair only — no gameplay effect.'),
('title_wholesale','Wholesale','title','rare',1200,false,'store','Rare title cosmetic. Flair only — no gameplay effect.'),
('title_untouchable','Untouchable','title','mythic',15000,false,'store','Mythic title cosmetic. Flair only — no gameplay effect.'),
('title_snitch_s_nightmare','Snitch''s Nightmare','title','rare',1200,false,'store','Rare title cosmetic. Flair only — no gameplay effect.'),
('title_certified','Certified','title','uncommon',500,false,'store','Uncommon title cosmetic. Flair only — no gameplay effect.'),
('title_heavy','Heavy','title','uncommon',500,false,'store','Uncommon title cosmetic. Flair only — no gameplay effect.'),
('title_on_sight','On Sight','title','common',250,false,'store','Common title cosmetic. Flair only — no gameplay effect.'),
('title_the_chemist','The Chemist','title','epic',3000,false,'store','Epic title cosmetic. Flair only — no gameplay effect.'),
('title_numbers_man','Numbers Man','title','rare',1200,false,'store','Rare title cosmetic. Flair only — no gameplay effect.'),
('title_weight_class','Weight Class','title','uncommon',500,false,'store','Uncommon title cosmetic. Flair only — no gameplay effect.'),
('title_first_of_the_month','First of the Month','title','common',250,false,'store','Common title cosmetic. Flair only — no gameplay effect.'),
('title_franchise','Franchise','title','legendary',7000,false,'store','Legendary title cosmetic. Flair only — no gameplay effect.'),
('title_the_fixer','The Fixer','title','epic',3000,false,'store','Epic title cosmetic. Flair only — no gameplay effect.'),
('title_retired_allegedly','Retired (Allegedly)','title','legendary',0,false,'earned','Legendary title cosmetic. Flair only — no gameplay effect.'),
('nameplate_concrete','Concrete','nameplate','common',250,false,'store','Common nameplate cosmetic. Flair only — no gameplay effect.'),
('nameplate_neon_alley','Neon Alley','nameplate','uncommon',500,false,'store','Uncommon nameplate cosmetic. Flair only — no gameplay effect.'),
('nameplate_evidence_locker','Evidence Locker','nameplate','rare',1200,false,'store','Rare nameplate cosmetic. Flair only — no gameplay effect.'),
('nameplate_rust_rain','Rust & Rain','nameplate','uncommon',500,false,'store','Uncommon nameplate cosmetic. Flair only — no gameplay effect.'),
('nameplate_blacktop','Blacktop','nameplate','common',250,false,'store','Common nameplate cosmetic. Flair only — no gameplay effect.'),
('nameplate_pill_bottle','Pill Bottle','nameplate','rare',1200,false,'store','Rare nameplate cosmetic. Flair only — no gameplay effect.'),
('nameplate_turnpike','Turnpike','nameplate','common',250,false,'store','Common nameplate cosmetic. Flair only — no gameplay effect.'),
('nameplate_riverfront','Riverfront','nameplate','uncommon',500,false,'store','Uncommon nameplate cosmetic. Flair only — no gameplay effect.'),
('nameplate_section_8','Section 8','nameplate','rare',1200,false,'store','Rare nameplate cosmetic. Flair only — no gameplay effect.'),
('nameplate_cut_corners','Cut Corners','nameplate','uncommon',500,false,'store','Uncommon nameplate cosmetic. Flair only — no gameplay effect.'),
('nameplate_cold_open','Cold Open','nameplate','epic',3000,false,'store','Epic nameplate cosmetic. Flair only — no gameplay effect.'),
('nameplate_static','Static','nameplate','common',250,false,'store','Common nameplate cosmetic. Flair only — no gameplay effect.'),
('nameplate_burner_static','Burner Static','nameplate','uncommon',500,false,'store','Uncommon nameplate cosmetic. Flair only — no gameplay effect.'),
('nameplate_trap_house_3am','Trap House 3AM','nameplate','epic',3000,false,'store','Epic nameplate cosmetic. Flair only — no gameplay effect.'),
('nameplate_gold_foil','Gold Foil','nameplate','legendary',0,true,'supporter','Legendary nameplate cosmetic. Flair only — no gameplay effect.'),
('frame_barbed_wire','Barbed Wire','frame','common',250,false,'store','Common frame cosmetic. Flair only — no gameplay effect.'),
('frame_chain_link','Chain Link','frame','common',250,false,'store','Common frame cosmetic. Flair only — no gameplay effect.'),
('frame_gold_chain','Gold Chain','frame','legendary',0,true,'supporter','Legendary frame cosmetic. Flair only — no gameplay effect.'),
('frame_police_tape','Police Tape','frame','uncommon',500,false,'store','Uncommon frame cosmetic. Flair only — no gameplay effect.'),
('frame_duct_tape','Duct Tape','frame','common',250,false,'store','Common frame cosmetic. Flair only — no gameplay effect.'),
('frame_neon_trim','Neon Trim','frame','rare',1200,false,'store','Rare frame cosmetic. Flair only — no gameplay effect.'),
('frame_brick','Brick','frame','uncommon',500,false,'store','Uncommon frame cosmetic. Flair only — no gameplay effect.'),
('frame_chrome','Chrome','frame','epic',3000,false,'store','Epic frame cosmetic. Flair only — no gameplay effect.'),
('frame_blood_money','Blood Money','frame','mythic',0,true,'supporter','Mythic frame cosmetic. Flair only — no gameplay effect.'),
('frame_founder_s_laurel','Founder''s Laurel','frame','exclusive',0,true,'supporter','Exclusive frame cosmetic. Flair only — no gameplay effect.'),
('accent_re_up_red','Re-Up Red','accent','uncommon',500,false,'store','Uncommon accent cosmetic. Flair only — no gameplay effect.'),
('accent_evidence_yellow','Evidence Yellow','accent','uncommon',500,false,'store','Uncommon accent cosmetic. Flair only — no gameplay effect.'),
('accent_money_green','Money Green','accent','rare',1200,false,'store','Rare accent cosmetic. Flair only — no gameplay effect.'),
('accent_cold_blue','Cold Blue','accent','common',250,false,'store','Common accent cosmetic. Flair only — no gameplay effect.'),
('accent_bruise_purple','Bruise Purple','accent','rare',1200,false,'store','Rare accent cosmetic. Flair only — no gameplay effect.'),
('accent_ash_grey','Ash Grey','accent','common',250,false,'store','Common accent cosmetic. Flair only — no gameplay effect.'),
('accent_uncut_white','Uncut White','accent','epic',3000,false,'store','Epic accent cosmetic. Flair only — no gameplay effect.'),
('accent_hazard_orange','Hazard Orange','accent','uncommon',500,false,'store','Uncommon accent cosmetic. Flair only — no gameplay effect.'),
('accent_solid_gold','Solid Gold','accent','legendary',0,true,'supporter','Legendary accent cosmetic. Flair only — no gameplay effect.'),
('accent_blackout','Blackout','accent','mythic',15000,false,'store','Mythic accent cosmetic. Flair only — no gameplay effect.'),
('badge_first_kilo','First Kilo','badge','common',0,false,'earned','Common badge cosmetic. Flair only — no gameplay effect.'),
('badge_clean_record','Clean Record','badge','rare',0,false,'earned','Rare badge cosmetic. Flair only — no gameplay effect.'),
('badge_ten_trips','Ten Trips','badge','uncommon',0,false,'earned','Uncommon badge cosmetic. Flair only — no gameplay effect.'),
('badge_marathon','Marathon','badge','epic',0,false,'earned','Epic badge cosmetic. Flair only — no gameplay effect.'),
('badge_made_man','Made Man','badge','legendary',0,false,'earned','Legendary badge cosmetic. Flair only — no gameplay effect.'),
('badge_survivor','Survivor','badge','epic',0,false,'earned','Epic badge cosmetic. Flair only — no gameplay effect.'),
('badge_high_roller','High Roller','badge','rare',0,false,'earned','Rare badge cosmetic. Flair only — no gameplay effect.'),
('badge_beta_pioneer','Beta Pioneer','badge','exclusive',0,false,'award','Exclusive badge cosmetic. Flair only — no gameplay effect.'),
('badge_bug_bounty','Bug Bounty','badge','exclusive',0,false,'award','Exclusive badge cosmetic. Flair only — no gameplay effect.'),
('badge_community_award','Community Award','badge','exclusive',0,false,'award','Exclusive badge cosmetic. Flair only — no gameplay effect.'),
('badge_ghost_never_seen','Ghost (Never Seen)','badge','mythic',0,false,'earned','Mythic badge cosmetic. Flair only — no gameplay effect.'),
('badge_founder','Founder','badge','exclusive',0,true,'supporter','Exclusive badge cosmetic. Flair only — no gameplay effect.'),
('marker_red_dot','Red Dot','marker','common',250,false,'store','Common marker cosmetic. Flair only — no gameplay effect.'),
('marker_crosshair','Crosshair','marker','uncommon',500,false,'store','Uncommon marker cosmetic. Flair only — no gameplay effect.'),
('marker_skull_pin','Skull Pin','marker','rare',1200,false,'store','Rare marker cosmetic. Flair only — no gameplay effect.'),
('marker_dollar_pin','Dollar Pin','marker','uncommon',500,false,'store','Uncommon marker cosmetic. Flair only — no gameplay effect.'),
('marker_ghost_pin','Ghost Pin','marker','epic',3000,false,'store','Epic marker cosmetic. Flair only — no gameplay effect.'),
('tag_re_up_tag','RE-UP Tag','tag','uncommon',500,false,'store','Uncommon tag cosmetic. Flair only — no gameplay effect.'),
('tag_crown_tag','Crown Tag','tag','rare',1200,false,'store','Rare tag cosmetic. Flair only — no gameplay effect.'),
('tag_wolf_tag','Wolf Tag','tag','rare',1200,false,'store','Rare tag cosmetic. Flair only — no gameplay effect.'),
('tag_skull_tag','Skull Tag','tag','uncommon',500,false,'store','Uncommon tag cosmetic. Flair only — no gameplay effect.'),
('tag_dollar_tag','Dollar Tag','tag','common',250,false,'store','Common tag cosmetic. Flair only — no gameplay effect.'),
('charm_burner_charm','Burner Charm','charm','common',250,false,'store','Common charm cosmetic. Flair only — no gameplay effect.'),
('charm_gold_grillz_charm','Gold Grillz Charm','charm','legendary',0,true,'supporter','Legendary charm cosmetic. Flair only — no gameplay effect.'),
('charm_evidence_tag_charm','Evidence Tag Charm','charm','uncommon',500,false,'store','Uncommon charm cosmetic. Flair only — no gameplay effect.')
on conflict (id) do update set name=excluded.name, rarity=excluded.rarity,
  cred_cost=excluded.cred_cost, supporter_only=excluded.supporter_only, source=excluded.source;
